### ISSUE TITLE
netlify doesn't rebuild `public`

### ISSUE THREAD

**Issue by yatesco** [yatesco/colinyates.co.uk#1]
It is too easy for forget to run `hugo` (which builds the public site) before committing. Given that netlify has been instructed to run `hugo` it shouldn't be necessary.

However, committing without running `hugo` means the `public` dir isn't updated and therefore the public site isn't either.

If it is necessary then either:
- add a script/elisp to automate it (which is also a great place to clean stale posts as well)
- add a circle-ci/travis-ci job to do it
- add a git post-hook

It would be preferred not to have to do any of those things by sorting out the netlify configuration.

Either way, stop relying on me remembering....

**Comment by kaushalmodi** [comment]
I ended up on this issue thread after seeing that you had starred the `ox-hugo` repo. Thanks! :)

The reason I ended up here is that I was curious to see you committed the `public/` dir too, even when you were using Netlify.

If you are using Netlify, you don't need to commit the public/ dir.. Netlify runs `hugo`, generates `public/` and publishes that, all automatically.

For example, this is the **complete** source of the https://ox-hugo.scripter.co site: https://github.com/kaushalmodi/ox-hugo/tree/master/doc

Note that I do not need to commit `public/`.

This is all I set in Netlify:

![image](https://user-images.githubusercontent.com/3578197/31460371-32434686-ae94-11e7-9dd8-2710acd797ee.png)

Hope that helps.. you don't need to deal with Circle CI or Travis or post-hook or anything like that.. just edit the Org source, export using `ox-hugo` and commit the Markdown files in `content/`. I commit the `content-org/` too just for the sake of data preservation by the inherent nature of `git`.. otherwise commit `content-org/` is not required either.

Hope that helps and you don't see this as an intrusion.

**Comment by yatesco** [comment]
Hey, that’s awesome - thanks!

**Comment by yatesco** [comment]
Nope, just tried it without committing to public and whilst I can see in the log that hugo is being run none of that makes it public.

I also tried `rm -rf public ; hugo` and that led to a blank site. 

Very bizarre.

@kaushalmodi  - do you mind if I experiment with your theme? I might literally clone your app and adjust if that is OK?

**Comment by kaushalmodi** [comment]
> I also tried rm -rf public ; hugo and that led to a blank site.

Aha, I think I know why..  You want to use the cocoa theme (right?), but reference to that repo is missing in your .gitmodules[1]. 

So when Netlify does a recursive clone reading your .gitmodules, it does not get the reference to cocoa. 

> @kaushalmodi - do you mind if I experiment with your theme? I might literally clone your app and adjust if that is OK?

Sure, I am just using the alabaster theme (I am not the original author) for the ox-hugo site, though *not* as a git submodule. The whole project is GPLv3 licensed. So feel free to use it. Though my gut feeling tells that you just need to fix the .gitmodules file. 

[1]: https://github.com/yatesco/colinyates.co.uk/blob/master/.gitmodules

**Comment by kaushalmodi** [comment]
To add, I'd suggest deleting the public dir completely in a test branch of your site, and commit that. Also fix the .gitmodules in that branch. 

Also add something like this to your netlify.toml so that you know that the correct version of hugo is being used for branch deploys too. 

```
[context.branch-deploy]
  publish = "public"
  command = "hugo version; hugo"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.28"
```

If your original netlify site name is **foo**.netlify.com, and the branch name is **xx**, that branch will be automatically published on **xx--foo.netlify.com**.

**Comment by yatesco** [comment]
Thanks @kaushalmodi - the `.gitmodules` was the problem. Thanks again for all your help :-).

**Comment by yatesco** [comment]
I think the `branch as site` only works if netlify are managing your DNS, which in my case they aren't.

**Comment by kaushalmodi** [comment]
Awesome! Glad you got it working :)

No, I am pretty sure it will work even if you don't manage your DNS through Netlify. Because in that example, you are still using netlify.com domain. 

When you publish your blog, it should be getting deployed on some foo.netlify.com, right?

Netlify gives a random name to that foo.. like *blistering-barnacles-11.netlify.com*. You just prefix that with your branch name followed by double-dashes. 

Example, for my main site https://scripter.co, I have set the Netlify site name to "scripter-co" (yes, you can rename the Netlify assigned random name like above to any available subdomain name you like..). So the same site is also on https://scripter-co.netlify.com. I use Chroma for syntax highlighting on my main site, but still use Pygments in a branch... Which I named pygments. So if you go to https://pygments--scripter-co.netlify.com, you will see the same site, but with code blocks highlighted using Pygments. As you see, my custom domain isn't involved anywhere in that. Also I am using the Netlify free tier. 

I am not a domain/DNS wiz, this is what I just recently learned.. so may be I am wrong :)
